[package]
name = "cathode"
version = "0.1.0"
authors = ["thor"]
edition = "2018"

[dependencies]
clap = "~2.27.0"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
yaml-rust = "0.4"